baseURL: "https://aviebrantz.com"
languageCode: "en-us"
title: "Alvaro Viebrantz"
theme: "PaperMod"

blackfriday:
    extensions: ["hardLineBreak"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false

googleAnalytics: UA-37452057-12

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Alvaro Viebrantz"
    description: "Developer Program Engineer, Data Analytics SDK at Google Cloud & Former Google Developer Expert for IoT"
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["https://avatars2.githubusercontent.com/u/1615543?v=3&s=320"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowBreadCrumbs: false
    disableSpecial1stPost: false
    comments: false
    hidemeta: false
    showtoc: false
    tocopen: false
    mainSections : ['articles', 'videos', 'talks']
    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Alvaro Viebrantz"
        #icon: /apple-touch-icon.png
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: Hi, I'm Alvaro
        subtitle: "Developer Program Engineer, Data Analytics SDK at Google Cloud & Former Google Developer Expert for IoT"
        imageUrl: "https://avatars2.githubusercontent.com/u/1615543?v=3&s=320"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
          - name: Talks
            url: talks
          - name: Articles
            url: articles
          - name: Videos
            url: videos
          - name: Projects
            url: projects
          - name: Tags
            url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi, I'm Alvaro \U0001F44B"
        Content: Developer Program Engineer, Data Analytics SDK at Google Cloud & Former Google Developer Expert for IoT. [More about me.](/about/)

    socialIcons:
        - name: twitter
          url: "https://twitter.com/alvaroviebrantz"
        #- name: stackoverflow
        #  url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/alvarowolfx"
        - name: youtube
          url: "https://youtube.com/alvaroviebrantz"
        - name: linkedin
          url: "https://br.linkedin.com/in/alvaro-viebrantz-55119048"
        - name: google
          url: "https://developers.google.com/community/experts/directory/profile/profile-alvaro_viebrantz"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: talks
          name: Talks
          url: /talks/
          weight: 10
        - identifier: articles
          name: Articles
          url: /articles/
          weight: 15
        - identifier: Videos
          name: Videos
          url: /videos/
          weight: 20
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 30
        - identifier: about
          name: About
          url: /about
          weight: 40
        #- identifier: tags
        #  name: tags
        #  url: /tags/
        #  weight: 50
